services:
  - type: web
    name: kronos-api-realocacao
    env: python
    rootDir: realocacao-api 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
