name: Processamento Diário de Ausências 

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  call_api_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Realocação Agendada (Render API)
        run: |
          echo "Chamando a API do Render para processar ausências agendadas..."
          curl -X POST \
          -H "Content-Type: application/json" \
          --max-time 90 \
          --fail \
          ${{ secrets.RENDER_API_REALOCACAO_URL }}
        env:
          RENDER_API_REALOCACAO_URL: ${{ secrets.RENDER_API_REALOCACAO_URL }}

      - name: Executar Devolução de tarefas (Render API)
        run: |
          echo "Chamando a API do Render para processar devoluções de tarefas..."
          curl -X POST \
          -H "Content-Type: application/json" \
          --max-time 90 \
          --fail \
          ${{ secrets.RENDER_API_DEVOLUCAO_URL }}
        env:
          RENDER_API_DEVOLUCAO_URL: ${{ secrets.RENDER_API_DEVOLUCAO_URL }}